steps:
  # Step 1: Build the container using Buildpacks
  - name: "gcr.io/k8s-skaffold/pack"
    args:
      - "build"
      - "gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA"
      - "--builder=gcr.io/buildpacks/builder:v1"
      - "--env=GOOGLE_RUNTIME=python"

  # Step 2: Push the image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA"]

  # Step 3: Deploy to Cloud Run with 4 CPUs and 1.5GiB memory
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "fastapi-app"
      - "--image=gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA"
      - "--region=us-central1" # Change as needed
      - "--platform=managed"
      - "--allow-unauthenticated" # Remove if authentication is needed
      - "--cpu=4"
      - "--memory=1.5Gi"

images:
  - "gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA"
