runtime: python312
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: B4

basic_scaling:
  max_instances: 5 # Set the maximum number of instances
  idle_timeout: 15m # Set idle timeout (adjust as needed)
